---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-shr-{{ template "github.repoShorthand" }}-{{ .Values.github.repository }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: gha-shr-{{ template "github.repoShorthand" }}-{{ .Values.github.repository }}
  template:
    metadata:
      labels:
        app: gha-shr-{{ template "github.repoShorthand" }}-{{ .Values.github.repository }}
    spec:
      serviceAccountName: gha-shr-{{ template "github.repoShorthand" }}-{{ .Values.github.repository }}
      containers:
        - name: actions-runner
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 10000
          env:
            - name: GITHUB_REPOSITORY
              value: {{ .Values.github.organisation }}/{{ .Values.github.repository }}
            - name: GITHUB_TOKEN
              value: {{ .Values.github.token }}
            - name: RUNNER_LABELS
              value: {{ .Values.runner.labels }}
          resources:
            limits:
              memory: 4000Mi
              cpu: 1000m
