name: Add issues to project
on:
  push:
    branches:
      - token-permission-fixes
  issues:
    types:
      - opened

permissions: read-all

jobs:
  add-to-project:
    permissions:
      issues: write
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85 # v0.4.0
        with:
          project-url: https://github.com/orgs/ministryofjustice/projects/27
          github-token: ${{ secrets.GITHUB_TOKEN }}