---
name: Release Data Platform Catalogue Python library

on:
  push:
    tags:
      - "python-library-data-platform-catalogue-v*.*.*"

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-libraries/data-platform-catalogue
    environment:
      name: data-platform-catalogue
    permissions:
      id-token: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Python 3.10
        id: setup_python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.10"

      - name: Install Poetry
        id: install_poetry
        run: |
          curl -sSL "https://install.python-poetry.org" | python3 -
          echo "${HOME}/.poetry/bin" >>"${GITHUB_PATH}"

      - name: Build a distribution
        id: build_distribution
        run: |
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450 # v1.8.14
        with:
          packages-dir: python-libraries/data-platform-catalogue/dist
