---
name: Containers path-filter configuration generator

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - "**/*Dockerfile*"

permissions: read-all

jobs:
  container-configuration-generator:
    if: github.actor != 'dependabot[bot]'
    name: Containers path-filter configuration generator
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Run Containers path-filter configuration generator
        id: generate_configuration
        run: bash -x scripts/path-filter/generator.sh containers
        env:
          GITHUB_TOKEN: ${{ secrets.DATA_PLATFORM_ROBOT_TOKEN }}
