---
name: Terraform - GitHub

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/terraform-data-engineering.yml
      - terraform/data-engineering/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-data-engineering.yml
      - terraform/data-engineering/**

permissions: read-all

jobs:
  terraform:
    name: Terraform
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      working-directory: terraform/data-engineering
      aws-role-to-assume: arn:aws:iam::042130406152:role/GlobalGitHubActionAccess
      terraform-version: 1.4.5
      terraform-backend-config-role: arn:aws:iam::042130406152:role/GlobalGitHubActionAdmin
    secrets: inherit
